version:  "3.5"

networks:
    netflow:
        external: true
services:
    twitterdscont:
        image: "twitterds:latest"
        networks:
          - netflow
        enviroment:
            KafkaServer: "http://kafkaserv:9092"
